version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: simulae
    volumes:
      - ./database:/var/lib/postgresql/data
  web:
    build: .
    entrypoint: docker-entrypoint.sh
    command: gunicorn -w 4 -b 0.0.0.0:8000 project.wsgi
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
