# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='references', verbose_name='Imagem')),
                ('link', models.URLField(verbose_name='Link')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('icon', models.FileField(blank=True, null=True, upload_to='subjects', verbose_name='Ícone')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'verbose_name': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.Subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name_plural': 'Tópicos',
                'verbose_name': 'Tópico',
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='subjects.Topic', verbose_name='Tópico'),
        ),
    ]
