# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Referência', 'verbose_name_plural': 'Referências'},
        ),
    ]
