# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name_plural': 'Respostas',
                'verbose_name': 'Resposta',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='choices', verbose_name='Imagem')),
                ('correct', models.BooleanField(verbose_name='Correta')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name_plural': 'Alternativas',
                'verbose_name': 'Alternativa',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Simulados',
                'verbose_name': 'Simulado',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='exams.Exam')),
            ],
            options={
                'verbose_name_plural': 'Questões do simulado',
                'verbose_name': 'Questão do simulado',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions', verbose_name='Imagem')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('hint', models.TextField(verbose_name='Explicação')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('subjects', models.ManyToManyField(related_name='questions', to='subjects.Subject', verbose_name='Disciplinas')),
                ('topics', models.ManyToManyField(related_name='questions', to='subjects.Topic', verbose_name='Tópicos')),
            ],
            options={
                'verbose_name_plural': 'Questões',
                'verbose_name': 'Questão',
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='exams.Question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Question', verbose_name='Questão atual'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', through='exams.ExamQuestion', to='exams.Question', verbose_name='Questões'),
        ),
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.Question', verbose_name='Questão'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.Choice', verbose_name='Alternativa'),
        ),
        migrations.AddField(
            model_name='answer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.Exam', verbose_name='Simulado'),
        ),
    ]
